//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_WebApi_asp.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderItem
    {
        public long orderItemID { get; set; }
        public Nullable<long> orderID { get; set; }
        public Nullable<int> itemID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual item item { get; set; }
        public virtual order order { get; set; }
    }
}
